version: '3.7'

x-env-postgres: &env-postgres
  POSTGRES_DB: teststudio_lite_db
  POSTGRES_USER: teststudio_lite_db_user
  POSTGRES_PASSWORD: iqb_tba_db_password_1

x-env-initdata: &env-initdata
  SUPERUSER_NAME: super
  SUPERUSER_PASSWORD: user123
  WORKSPACE_NAME: sample_workspace

services:
  teststudio-lite-db-dev:
    image: postgres:9.6
    container_name: teststudio-lite-db-dev
    environment:
      <<: *env-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./config/sql/:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"

  teststudio-lite-backend-dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: teststudio-lite-backend-dev
    environment:
      <<: *env-postgres
      <<: *env-initdata
      POSTGRES_HOST: teststudio-lite-db-dev
      POSTGRES_PORT: 5432
    depends_on:
      - teststudio-lite-db-dev
    volumes:
      - ../:/var/www/html/
      - vo_tmp:/var/www/html/vo_tmp
      - itemplayers:/var/www/html/itemplayers
      - itemauthoringtools:/var/www/html/itemauthoringtools
    ports:
      - "8081:80"
    stdin_open: true
    tty: true

volumes:
  dbdata:
  vo_tmp:
  itemplayers:
  itemauthoringtools:
