version: '3.8'

x-env-postgres: &env-postgres
  POSTGRES_DB: teststudio_lite_db
  POSTGRES_USER: teststudio_lite_db_user
  POSTGRES_PASSWORD: iqb_tba_db_password_1

x-env-initdata: &env-initdata
  SUPERUSER_NAME: super
  SUPERUSER_PASSWORD: user123
  WORKSPACE_GROUP_NAME: sample_workspace_group
  WORKSPACE_NAME: sample_workspace

services:
  teststudio-lite-db-dev:
    image: postgres:9.6
    container_name: teststudio-lite-db-dev
    environment:
      <<: *env-postgres
      <<: *env-initdata
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./config/sql/:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"

  teststudio-lite-backend-dev:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: teststudio-lite-backend-dev
    environment:
      <<: *env-postgres
      POSTGRES_HOST: teststudio-lite-db-dev
      POSTGRES_PORT: 5432
    depends_on:
      - teststudio-lite-db-dev
    volumes:
      - ../:/var/www/html/
      - vo_tmp:/var/www/html/vo_tmp
      - verona-modules:/var/www/html/verona-modules
      - config:/var/www/html/config
    ports:
      - "8081:80"
    stdin_open: true
    tty: true

volumes:
  dbdata:
  vo_tmp:
  verona-modules:
  config:
